stages:
  - install
  - test
  - build

variables:
  BUILD_COMMIT: $CI_COMMIT_SHORT_SHA
  BUILD_BRANCH: $CI_COMMIT_REF_NAME
  BUILD_NUMBER: $CI_PIPELINE_IID
  BUILD_VERSION: $CI_COMMIT_TAG
  BUILD_DEV_RELEASE: 0.0.0-dev
  GO_PACKAGE: github.com/mysteriumnetwork/node
  GIT_CLONE_PATH: /home/gitlab-runner/go/src/$GO_PACKAGE
  GOFLAGS: "-count=1" # Supersedes GOCACHE=off, see: https://github.com/golang/go/issues/29378#issuecomment-449383809

cache:
  key: vendor
  untracked: true
  policy: pull
  paths:
    - vendor/

before_script:
  - if [ -z "$BUILD_VERSION" ]; then
    export BUILD_VERSION=$BUILD_DEV_RELEASE;
    fi
  - dep ensure -v

after_script:
  # docker based jobs leave files owned by root
  - sudo chown -R gitlab-runner:gitlab-runner $GOPATH

install-deps:
  stage: install
  tags:
    - go
  cache:
    key: vendor
    untracked: true
    policy: pull-push
    paths:
      - vendor/
  script:
    - >
      go get \
        github.com/debber/debber-v0.3/cmd/debber \
        golang.org/x/lint/golint \
        golang.org/x/tools/cmd/goimports \
        github.com/go-swagger/go-swagger/cmd/swagger

checks:
  stage: test
  tags:
    - go
  script:
    - bin/check_golint
    - bin/check_goimports
    - bin/check_license
    - bin/check_govet
    - bin/check_swagger

test:
  stage: test
  tags:
    - go
  script:
    - bin/test

test-e2e:
  stage: test
  tags:
    - go
  script:
    - bin/test_e2e

package:linux-amd64:
  stage: build
  tags:
    - go
  script:
    - BINARY=build/myst/myst_linux_amd64 bin/package_standalone linux amd64

package:ios:
  stage: build
  tags:
    - go
  script:
    - bin/package_ios amd64

package:android:
  stage: build
  tags:
    - go
  script:
    - bin/package_android amd64
