sudo: false
language: go

go:
  - 1.9.2
go_import_path: github.com/mysterium/node

env:
  global:
    - TRAVIS_TOOLS_PATH=$HOME/travis_tools
    - GLIDE_HOME=$HOME/glide-home

cache:
  directories:
  - $TRAVIS_TOOLS_PATH #cache our binary tools for travis
  - $GLIDE_HOME #cache glide home dir

install:
  - source bin/travis_scripts/setup_tools_dir
  - source bin/travis_scripts/ensure_glide
  - glide "-home" $GLIDE_HOME install
#This is actual build/test command
script: bin/test