sudo: false
language: go

go:
  - 1.9.2
go_import_path: github.com/mysterium/node
#This is called when travis pulls project dependencies - ugly git checkout freezes glide version (0.13.1)
install:
  - go get -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && git checkout 67790b3dbede72cfdc54aa53be4706322c9499e0 && go install && cd -
  - glide install
#This is actual build/test command
script: go test -v -cover ./...