sudo: false
language: go

go:
  - 1.9.2
go_import_path: github.com/mysterium/node

env:
  global:
    - CACHE_ROOT_DIR=$HOME/cache
    - BUILD_TOOLS_PATH=$CACHE_ROOT_DIR/build_tools
    #don't cache glide dependencies yet - it always triggers cache changes and slows down build even more, something to do with git index files
    - GLIDE_HOME=$HOME/glide-home

cache:
  directories:
  - $CACHE_ROOT_DIR #cache everything in cache root dir

before_install:
  - rm -f .env
  - echo "MYSTERIUM_API_URL=$MYSTERIUM_API_URL" >> .env
  - echo "NATS_SERVER_IP=$NATS_SERVER_IP" >> .env
install:
  #setups PATH variable to contain travis tools dir and creates directory if needed (it could be already created by cache setup)
  - source bin/travis_scripts/setup_tools_dir.sh $BUILD_TOOLS_PATH
  #ensure that we have glide (possibly from cache) or setup a fresh one
  - source bin/travis_scripts/ensure_glide.sh $BUILD_TOOLS_PATH "v0.13.1"
  #run glide dependencies setup (it takes about 52 secs to download it from scratch)
  - glide "-home" $GLIDE_HOME install

#This is actual build/test command
script: bin/test && bin/client_build && bin/server_build

before_deploy:
  - mkdir binaries
  - cp build/client/mysterium_client binaries/mysterium_client_$TRAVIS_OS_NAME
  - cp build/server/mysterium_server binaries/mysterium_server_$TRAVIS_OS_NAME

deploy:
  - provider: pages
    local-dir: binaries
    skip-cleanup: true
    github-token: "$GIT_RELEASES_API_KEY"
    keep-history: true
    repo: MysteriumNetwork/build-artifacts
    on:
      branch: improvement/upload-mysterium-binaries-on-master-branch-commit #change this to master if it works

  - provider: releases
    file:
      - "build/client/mysterium_client"
      - "build/server/mysterium_server"
    skip_cleanup: true
    api_key: "$GIT_RELEASES_API_KEY"
    on:
      tags: true
      branch: master