version: '2'
services:

  broker:
    image: nats
    container_name: mysterium-broker
    networks:
      - default
    ports:
      - 4222:4222
      - 8222:8222

  server-ubuntu:
    build:
      context: .
      dockerfile: bin/server_docker/ubuntu/Dockerfile
      args:
        PACKAGE_FILE: build/package/mysterium-node_linux_amd64.deb
    container_name: mysterium-server-ubuntu
    depends_on:
      - broker
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - default
    ports:
      - 1194:1194
    environment:
      NODE: server-ubuntu

  server-golang:
    build:
      context: .
      dockerfile: bin/server_docker/golang_alpine/Dockerfile
    container_name: mysterium-server-golang
    depends_on:
      - broker
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - default
    volumes:
      - .:/go/src/github.com/mysterium/node
    environment:
      NODE: server-golang

  server-alpine:
    build:
      context: .
      dockerfile: bin/server_docker/alpine/Dockerfile
    container_name: mysterium-node-alpine
    depends_on:
      - broker
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - default
    environment:
      NODE: server-alpine

  client:
    build:
      context: .
      dockerfile: bin/client_docker/ubuntu/Dockerfile
      args:
        PACKAGE_FILE: build/package/mysterium-client_linux_amd64.deb
    container_name: mysterium-client
    depends_on:
      - broker
      - server-ubuntu
      - server-golang
      - server-alpine
    networks:
      - default
    environment:
      NODE: server-ubuntu