version: '2'
services:

  server:
    build:
      context: .
      dockerfile: bin/server_docker/ubuntu/Dockerfile
      args:
        PACKAGE_FILE: build/package/mysterium-node_linux_amd64.deb
    container_name: mysterium-server
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - default
    ports:
      - 1194:1194
    environment:
      - NODE=123456

  client:
    build:
      context: .
      dockerfile: bin/client_docker/ubuntu/Dockerfile
      args:
        PACKAGE_FILE: build/package/mysterium-client_linux_amd64.deb
    container_name: mysterium-client
    networks:
      - default

  gateway:
    image: nats
    container_name: mysterium-gateway
    networks:
      - default
    ports:
      - 4222:4222
      - 8222:8222