version: '2'
services:

  broker:
    tty: true
    image: nats
    container_name: mysterium-broker
    networks:
      - default
    ports:
      - 4222:4222
      - 8222:8222

  server-ubuntu:
    privileged: true
    tty: true
    build:
      context: .
      dockerfile: bin/server_docker/ubuntu/Dockerfile
      args:
        PACKAGE_VERSION: 0.0.1-docker
    container_name: mysterium-server-ubuntu
    depends_on:
      - broker
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - default
    ports:
      - 1194:1194
    environment:
      MYSTERIUM_SERVER_IDENTITY: ""
      MYSTERIUM_SERVER_IDENTITY_PASSPHRASE: ""
      MYSTERIUM_DISCOVERY_ADDRESS: ""
      MYSTERIUM_BROKER_ADDRESS: ""

  client:
    privileged: true
    tty: true
    build:
      context: .
      dockerfile: bin/client_docker/ubuntu/Dockerfile
      args:
        PACKAGE_VERSION: 0.0.1-docker
    container_name: mysterium-client
    depends_on:
      - broker
      - server-ubuntu
    networks:
      - default
    ports:
      - 4050:4050
    environment:
      MYSTERIUM_CLIENT_TEQUILAPI_PORT: 4050
      MYSTERIUM_DISCOVERY_ADDRESS: ""
