version: '2'
services:

  broker:
    image: nats
    ports:
      - 4222:4222
      - 8222:8222

  server-alpine:
    build:
      context: .
      dockerfile: bin/server_docker/alpine/Dockerfile
    depends_on:
      - broker
    cap_add:
      - NET_ADMIN
    ports:
      - 11941:1194
    environment:
      - AGREED_TERMS_AND_CONDITIONS
    command: -agreed-terms-and-conditions=04-06-2018

  server-ubuntu:
    build:
      context: .
      dockerfile: bin/server_docker/ubuntu/Dockerfile
      args:
        PACKAGE_VERSION: 0.0.1-docker
    depends_on:
      - broker
    cap_add:
      - NET_ADMIN
    ports:
      - 11942:1194
    environment:
      - AGREED_TERMS_AND_CONDITIONS
    command: -agreed-terms-and-conditions=04-06-2018

  client-alpine:
    build:
      context: .
      dockerfile: bin/client_docker/alpine/Dockerfile
    ports:
      - 40501:4050

  client-ubuntu:
    build:
      context: .
      dockerfile: bin/client_docker/ubuntu/Dockerfile
      args:
        PACKAGE_VERSION: 0.0.1-docker
    ports:
      - 40502:4050
