version: '3'
services:

  broker:
    image: nats
    expose:
      - 4222
      - 8222

  #infrastructure - centralized api and db
  db:
    image: percona:5.7
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api

  discovery:
    image: mysteriumnetwork/mysterium-api:0.1.12
    expose:
    - 80
    environment:
      APP_PORT: 80
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
    depends_on:
    - db
