version: '2'
services:

  broker:
    image: nats
    expose:
      - 4222
      - 8222

  node:
    build:
      context: ..
      dockerfile: e2e/Dockerfile.node
    depends_on:
      - broker
    privileged: true
    cap_add:
      - MKNOD
      - NET_ADMIN
    expose:
      - 1194
    command: "--data-dir=/mysterium --config-dir=/mysterium/server_config --runtime-dir=/mysterium --broker-address=broker"

  client:
    build:
      context: ..
      #this effectively reuses node image built earlier
      dockerfile: e2e/Dockerfile.node
    depends_on:
      - broker
      - node
    privileged: true
    cap_add:
      - MKNOD
      - NET_ADMIN
    ports:
      - 4052:4050
    entrypoint:
      "/mysterium/mysterium_client"
    command:
      "--data-dir=/mysterium --config-dir=/mysterium/client_config --runtime-dir=/mysterium
      --discovery-address=http://notyetdefined:9999 --tequilapi.address=0.0.0.0 --tequilapi.port=4050"
