version: '3'
services:

  broker:
    image: nats
    networks:
      - testnet
    expose:
      - 4222
      - 8222

  node:
    build:
      context: ..
      dockerfile: bin/server_docker/alpine/Dockerfile
    depends_on:
      - broker
      - discovery
      - ipify
    privileged: true
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - testnet
    expose:
      - 1194
    environment:
      MYSTERIUM_BROKER_ADDRESS: "broker"
      MYSTERIUM_DISCOVERY_ADDRESS: "http://discovery/v1"
      MYSTERIUM_SERVER_COUNTRY: "e2e-land"
    command: "--ipify-url=http://ipify:3000"

  client:
    build:
      context: ..
      dockerfile: bin/client_docker/alpine/Dockerfile
    depends_on:
      - broker
      - node
      - discovery
      - ipify
    privileged: true
    cap_add:
      - MKNOD
      - NET_ADMIN
    networks:
      - testnet
    ports:
      - 4052:4050
    command: "--ipify-url=http://ipify:3000 --discovery-address=http://discovery/v1"

  #infrastructure - centralized api and db
  db:
    image: percona:5.7
    restart: always
    networks:
      - testnet
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api

  discovery:
    image: mysteriumnetwork/mysterium-api:0.1.6
    networks:
      - testnet
    expose:
    - 80
    environment:
      APP_PORT: 80
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
    depends_on:
    - db
  #'external' IP detection
  ipify:
    image: owlab/ipify
    networks:
      - testnet
    expose:
    - 3000

  #define internal network - isolated from outside
networks:
  testnet:
    internal: true