name: E2E tests
on:
  workflow_run:
    workflows: [Unit tests and linters]
    types: [completed]

jobs:
  e2e-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: E2E basic test
        run: go run mage.go -v TestE2EBasic

      - name: E2E NAT test
        run: go run mage.go -v TestE2ENAT
